---
title: " "
output:
  html_document:
    css: app.css
runtime: shiny
---

```{r libs, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}

library(shiny)
library(forcats)
library(tidyverse)

icpBHTAgg <- read_csv("data/icpBHTAgg.csv")

```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}
choices <- icpBHTAgg$Name %>% sort()

# picular.co/desert
# highlight <- "#DF9A42"
highlight <- "#EC7726"
# background <- "#84543D"
background <- "#77C3FA"

# icpBHT$fill <- "black"
# icpBHT$alpha <- .25

pos <- position_jitter(height=.15, seed=5)


icpBHTreordered <- icpBHTAgg %>% filter(ccode != "USA") %>% arrange(priceIndex)
ints <- rep(1:length(unique(icpBHTreordered$ccode)), each=length(unique(icpBHTreordered$Name)))
icpBHTreordered$ccodeInt <- ints
icpBHTreordered$ccodeIntJit <- jitter(icpBHTreordered$ccodeInt, factor=.75)
# icpBHTreordered %>% select(ccodeInt, ccodeIntJit)

# define app
pricesApp <- function() {

  library(shiny)  

  shinyApp(
    ui <- fluidPage(
      fluidRow(
        column(9, plotOutput("pricePlot")),
        column(3, selectizeInput("categories", "Highlight Products:", choices, multiple=TRUE))
        )
    ),

    server <- function(input, output, session) {
      
      # data <- reactive({
      #   
      #   print(input$categories)
      # 
      #   # icpBHT$fill <- "black"
      #   # icpBHT$alpha <- 1
      #   
      #   icpBHT$Fill <- ifelse(icpBHT$Name %in% input$categories, highlight, background)
      #   icpBHT$Alpha <- ifelse(icpBHT$Name %in% input$categories, 1, .25)
      #   icpBHT
      #   
      # })
      
      dataBackground <- reactive({
          icpBHTreordered %>% filter(!(icpBHTreordered$Name %in% input$categories))
      })
      
      dataHighlight <- reactive({
          icpBHTreordered %>% filter(icpBHTreordered$Name %in% input$categories)
      })
      
      output$pricePlot <- renderPlot({
        
        ggplot() +
          geom_vline(xintercept = 1, lty=2) +
          geom_point(data=dataBackground(), aes(x=pppReal, y=ccodeIntJit, size=expShareT), alpha=.25, fill=background,
                      color="black", pch=21) +
          geom_point(data=dataHighlight(), aes(x=pppReal, y=ccodeIntJit, size=expShareT), alpha=1, fill=highlight, 
                      color="black", pch=21) +
          scale_y_discrete(breaks=unique(icpBHTreordered$ccodeInt), labels=unique(icpBHTreordered$ccode), 
                           limits=seq(1, length(unique(icpBHTreordered$ccode)))) +
          scale_size_area() +
          lims(x=c(0,5)) +
          labs(title="Prices by Product", subtitle="Relative to United States (1). Data from World Bank, ICP. Size indicates consumers' relative expenditure.", x="Price Index", y="Country") +
          theme_classic() +
          guides(size=FALSE)
        
      })
      
    })
}

```

```{r, warning=FALSE, message=FALSE, echo = FALSE}
pricesApp()
```