---
title: Estimating Policy Barriers to Trade
author: Brendan Cooley
date: 31 March 2019
abstract: To what extent is international trade free and fair? Because policy barriers to trade are often opaque and take on many forms, it is difficult to answer this question while relying on data on observable trade barriers. Here, I propose and implement a structural approach to estimating the magnitude of policy barriers to trade, measured at the trade partner level. The method allows for the possibility that these barriers are both *asymmetric* and *discriminatory*, affecting certain trade partners disproportionately. The approach reveals substantial latent policy barriers to trade, many times larger than observed tariffs. It also implies substantial effective policy discrimination, with exporters in subset of favored countries enjoying far superior market access conditions than their peers in unfavored countries. Combined, these results suggest that the existing world trading system remains far from a free and fair ideal.
thanks: Ph.D. candidate, Department of Politics, Princeton University. Princeton's Research Program in Political Economy provided financial support for this research. The World Bank's International Comparison Program kindly shared data. Thanks to Haosen Ge, Gene Grossman, Marco Martini, Helen Milner, Sayumi Miyano, Steve Monroe, Sondre Solstad, Kris Ramsay, Steve Redding, Alexandra Zeitz, Grace Zeng for comments on earlier drafts of this paper, as well as an audience at the Princeton Political Economy Graduate Colloquium.
# jelcodes: JEL codes go here

bibliography: /Users/brendancooley/Dropbox/References/library.bib
biblio-style: apsr

papersize: letter
documentclass: article
geometry: margin=1.25in
link-citations: true

output:
	fig_caption: yes
    citation_package: natbib

---

```{r libs, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}

rm(list=ls())
libs <- c('tidyverse', "stargazer", "countrycode", "knitr", "ggrepel", "patchwork", "ggthemes", "latex2exp", "readxl", "kableExtra")
sapply(libs, require, character.only = TRUE)

```

\newpage

# Introduction

```{r, child = 'sections/introduction.rmd'}
```

# Model

```{r, child = "sections/model.rmd"}
```

# Calibration

```{r, child = "sections/calibration.rmd"}
```

# Results

```{r, child = "sections/results.rmd"}
```

# Conclusion

```{r, child = "sections/conclusion.md"}
```

\clearpage

# Appendix

## Empirical Price Index: Estimating CES Taste Parameters

```{r, child = "sections/AcesTastes.md"}
```

## Modeling Freight Costs and Data Sources

```{r, child = "sections/AfreightModel.md"}
```

## Freight Cost Results

```{r, child = "sections/AfreightResults.rmd"}
```

## Sample Countries

```{r, child = "sections/AsampleCountries.rmd"}
```

## International Comparison Program Expenditure Categories

```{r, child = "sections/AicpCategories.rmd"}
```

\clearpage

# References
