---
title: "Estimating Policy Barriers to Trade"
date: "22 November 2019"
author: Brendan Cooley
position: Ph.D. Candidate
institution: Princeton University
email: "bcooley (at) princeton.edu"

bibliography: /Users/brendancooley/Dropbox (Princeton)/References/library.bib
biblio-style: apsr

backgroundTitle: "03_figs/title/containerDark.jpg"

output:
  revealjs::revealjs_presentation:
    template: "css/cooley-reveal.html"
    css: "css/cooley-reveal.css"
    backgroundTransition: none
    transition: none
    self_contained: false
    # reveal_plugins: ["notes"]
    lib_dir: index_files
    fig_caption: true
    reveal_options:
      slideNumber: false
      progress: false
      controls: true
---

```{r libs, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}
# TODO: speaker notes don't work with incremental reveal

# NOTE: need to set self_contained: false and ship accompanying files with index.html to website.
# Then make sure to publish page on Github settings

# image credit: https://www.photolib.noaa.gov/htmls/ship2059.htm
# Strait of Gibraltar

# control slides from phone
# http://remot.io/

source("01_code/params.R")

library(tidyverse)
library(patchwork)

figs_dir <- "03_figs/"
code_dir <- "01_code/"
shiny <- FALSE

```

```{r, child = "06_slides/introduction.rmd"}
```

```{r, child = "06_slides/model.rmd"}
```

```{r, child = "06_slides/prices.rmd"}
```

```{r, child = "06_slides/data.rmd"}
```

```{r, child = "06_slides/results.rmd"}
```

```{r, child = "06_slides/robustness.rmd"}
```

```{r, child = "06_slides/implications.rmd"}
```

```{r, child = "06_slides/conclusion.rmd"}
```

# Thank You {.aligncenter}

[brendancooley.com](http://brendancooley.com)

[bcooley@princeton.edu](bcooley@princeton.edu)

# Table of Contents

<div id="left">

**Sections**

1. <a href="#/intro">Introduction</a>
2. <a href="#/model">Model</a>
3. <a href="#/identification">Identification</a>
4. <a href="#/measurement">Data and Measurement</a>
5. <a href="#/results">Results</a>
6. <a href="#/robustness">Robustness</a>
7. <a href="#/implications">Implications</a>
8. <a href="#/conclusion">Conclusion</a>

</div>

<div id="right">

**Quick Links**

1. <a href="#/triIncome">Tariffs, TRI, and GDP</a>
2. <a href="#/tcostMap">Prices and Trade Costs</a>
3. <a href="#/shares">Expenditure Shares</a>
4. <a href="#/priceLevels">Price Levels</a>
5. <a href="#/freightCosts">Freight Costs</a>
6. <a href="#/magnitudes">Trade Barrier Magnitudes</a>
7. <a href="#/TRI">TRI and GDP</a>
8. <a href="#/MAI">MAI and GDP</a>
9. <a href="#/euPlacebo">EU Placebo</a>
10. <a href="#/blocs">Economic Blocs</a>
11. <a href="#/frechet">Fréchet Distribution</a>

</div>

```{r, child = "06_slides/appendix.rmd"}
```